version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${TARGET:-dev}
    environment:
      - PORT=5000
      - POSTGRES_DB_URL=postgresql://postgres:apassword@postgres
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ./src:/usr/src/app/src
    depends_on: 
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: none
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on: 
      - postgres
volumes:
  pgdata: