version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${TARGET:-test}
    environment:
      - PORT=5000
      - POSTGRES_DB_URL=postgresql://postgres:apassword@postgres
    ports:
      - "9230:9229"
    depends_on: 
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apassword